# Generated by Django 3.2.4 on 2021-06-22 16:14

from django.db import migrations


def forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")
    db_alias = schema_editor.connection.alias

    blogger = Group.objects.using(db_alias).create(name="Blogger")
    viewer = Group.objects.using(db_alias).create(name="Viewer")

    blog_permissions = Permission.objects.using(db_alias).filter(codename__endswith='_post')
    comment_permissions = Permission.objects.using(db_alias).filter(codename__endswith='_comment')

    for perm in blog_permissions:
        blogger.permissions.add(perm)
    blogger.save()

    for perm in comment_permissions:
        viewer.permissions.add(perm)
    viewer.save()


def reverse_func(apps, schema_editor):
    # forwards_func() creates two Country instances,
    # so reverse_func() should delete them.
    Group = apps.get_model("auth", "Group")
    db_alias = schema_editor.connection.alias
    Group.objects.using(db_alias).filter(name='Blogger').delete()
    Group.objects.using(db_alias).filter(name='Viewer').delete()


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
